baseURL = ""
title = "Dotfair"
enableRobotsTXT = true
# this example loads the theme as hugo module
# comment out line below, and uncomment the line after it if you prefer to load the theme normally
theme = "compose"
# theme = "compose"
enableGitInfo = false

# disableKinds = ["taxonomy", "taxonomyTerm"]
logo = "images/logo-dotfair.svg"
[outputs]
home = ["HTML", "RSS","JSON"]

fallBackOgImage = "images/logo-dotfair.svg"